set(source_list
src/main.c
src/vkx/vkx_sync.c
src/vkx/vkx_core.c
src/vkx/vkx_swap_chain.c
src/vkx/vkx_init.c
src/vkx/vkx_pipeline.c
src/io.c
)
set(header_list
include/io.h
include/vendor/stb_image.h
include/vkx/vkx.h
include/vkx/vkx_sync.h
include/vkx/vkx_core.h
include/vkx/vkx_swap_chain.h
include/vkx/vkx_init.h
include/vkx/vkx_pipeline.h
)
